### ISSUE TITLE
Some graphics?

### ISSUE THREAD

**Issue by cormullion** [julia-users-helsinki/julia-users-helsinki.github.io#1]
I won't be able to attend, but I thought I'd try to make a graphic, since Helsinki has such a well-known graphic identity.

![juh](https://user-images.githubusercontent.com/52289/188602739-a2bc4cbb-16f3-4c9a-be52-be0dfdc42824.png)

The Julia code to draw this is [here](https://gist.github.com/cormullion/bdf99c94335fcc4acb042833526206df).

**Comment by lucaferranti** [comment]
That's beautiful, thank you! I also thought it would be nice to have a logo or something, I'll add this to the webpage.

**Comment by lucaferranti** [comment]
the logo is up and running on the webpage : https://julia-users-helsinki.github.io/ thank you very much @cormullion for doing this! If you ever happen to be in Helsinki area, feel free to join our meetups 😄  🇫🇮
